# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/other/xtp_trade

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/other/xtp_trade

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/other/xtp_trade/CMakeFiles /root/other/xtp_trade/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/other/xtp_trade/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named XTPApiDemo

# Build rule for target.
XTPApiDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 XTPApiDemo
.PHONY : XTPApiDemo

# fast build rule for target.
XTPApiDemo/fast:
	$(MAKE) -f CMakeFiles/XTPApiDemo.dir/build.make CMakeFiles/XTPApiDemo.dir/build
.PHONY : XTPApiDemo/fast

FileUtils.o: FileUtils.cpp.o

.PHONY : FileUtils.o

# target to build an object file
FileUtils.cpp.o:
	$(MAKE) -f CMakeFiles/XTPApiDemo.dir/build.make CMakeFiles/XTPApiDemo.dir/FileUtils.cpp.o
.PHONY : FileUtils.cpp.o

FileUtils.i: FileUtils.cpp.i

.PHONY : FileUtils.i

# target to preprocess a source file
FileUtils.cpp.i:
	$(MAKE) -f CMakeFiles/XTPApiDemo.dir/build.make CMakeFiles/XTPApiDemo.dir/FileUtils.cpp.i
.PHONY : FileUtils.cpp.i

FileUtils.s: FileUtils.cpp.s

.PHONY : FileUtils.s

# target to generate assembly for a file
FileUtils.cpp.s:
	$(MAKE) -f CMakeFiles/XTPApiDemo.dir/build.make CMakeFiles/XTPApiDemo.dir/FileUtils.cpp.s
.PHONY : FileUtils.cpp.s

Main_Func.o: Main_Func.cpp.o

.PHONY : Main_Func.o

# target to build an object file
Main_Func.cpp.o:
	$(MAKE) -f CMakeFiles/XTPApiDemo.dir/build.make CMakeFiles/XTPApiDemo.dir/Main_Func.cpp.o
.PHONY : Main_Func.cpp.o

Main_Func.i: Main_Func.cpp.i

.PHONY : Main_Func.i

# target to preprocess a source file
Main_Func.cpp.i:
	$(MAKE) -f CMakeFiles/XTPApiDemo.dir/build.make CMakeFiles/XTPApiDemo.dir/Main_Func.cpp.i
.PHONY : Main_Func.cpp.i

Main_Func.s: Main_Func.cpp.s

.PHONY : Main_Func.s

# target to generate assembly for a file
Main_Func.cpp.s:
	$(MAKE) -f CMakeFiles/XTPApiDemo.dir/build.make CMakeFiles/XTPApiDemo.dir/Main_Func.cpp.s
.PHONY : Main_Func.cpp.s

Signal.o: Signal.cpp.o

.PHONY : Signal.o

# target to build an object file
Signal.cpp.o:
	$(MAKE) -f CMakeFiles/XTPApiDemo.dir/build.make CMakeFiles/XTPApiDemo.dir/Signal.cpp.o
.PHONY : Signal.cpp.o

Signal.i: Signal.cpp.i

.PHONY : Signal.i

# target to preprocess a source file
Signal.cpp.i:
	$(MAKE) -f CMakeFiles/XTPApiDemo.dir/build.make CMakeFiles/XTPApiDemo.dir/Signal.cpp.i
.PHONY : Signal.cpp.i

Signal.s: Signal.cpp.s

.PHONY : Signal.s

# target to generate assembly for a file
Signal.cpp.s:
	$(MAKE) -f CMakeFiles/XTPApiDemo.dir/build.make CMakeFiles/XTPApiDemo.dir/Signal.cpp.s
.PHONY : Signal.cpp.s

quote_spi.o: quote_spi.cpp.o

.PHONY : quote_spi.o

# target to build an object file
quote_spi.cpp.o:
	$(MAKE) -f CMakeFiles/XTPApiDemo.dir/build.make CMakeFiles/XTPApiDemo.dir/quote_spi.cpp.o
.PHONY : quote_spi.cpp.o

quote_spi.i: quote_spi.cpp.i

.PHONY : quote_spi.i

# target to preprocess a source file
quote_spi.cpp.i:
	$(MAKE) -f CMakeFiles/XTPApiDemo.dir/build.make CMakeFiles/XTPApiDemo.dir/quote_spi.cpp.i
.PHONY : quote_spi.cpp.i

quote_spi.s: quote_spi.cpp.s

.PHONY : quote_spi.s

# target to generate assembly for a file
quote_spi.cpp.s:
	$(MAKE) -f CMakeFiles/XTPApiDemo.dir/build.make CMakeFiles/XTPApiDemo.dir/quote_spi.cpp.s
.PHONY : quote_spi.cpp.s

trade_spi.o: trade_spi.cpp.o

.PHONY : trade_spi.o

# target to build an object file
trade_spi.cpp.o:
	$(MAKE) -f CMakeFiles/XTPApiDemo.dir/build.make CMakeFiles/XTPApiDemo.dir/trade_spi.cpp.o
.PHONY : trade_spi.cpp.o

trade_spi.i: trade_spi.cpp.i

.PHONY : trade_spi.i

# target to preprocess a source file
trade_spi.cpp.i:
	$(MAKE) -f CMakeFiles/XTPApiDemo.dir/build.make CMakeFiles/XTPApiDemo.dir/trade_spi.cpp.i
.PHONY : trade_spi.cpp.i

trade_spi.s: trade_spi.cpp.s

.PHONY : trade_spi.s

# target to generate assembly for a file
trade_spi.cpp.s:
	$(MAKE) -f CMakeFiles/XTPApiDemo.dir/build.make CMakeFiles/XTPApiDemo.dir/trade_spi.cpp.s
.PHONY : trade_spi.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... XTPApiDemo"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... FileUtils.o"
	@echo "... FileUtils.i"
	@echo "... FileUtils.s"
	@echo "... Main_Func.o"
	@echo "... Main_Func.i"
	@echo "... Main_Func.s"
	@echo "... Signal.o"
	@echo "... Signal.i"
	@echo "... Signal.s"
	@echo "... quote_spi.o"
	@echo "... quote_spi.i"
	@echo "... quote_spi.s"
	@echo "... trade_spi.o"
	@echo "... trade_spi.i"
	@echo "... trade_spi.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

